# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[](bold white)$time
[=========================================>](bold white)
[](bold white)$username$hostname$directory$git_branch$git_commit$git_state$git_metrics$git_status$docker_context$package$sudo$cmd_duration$jobs$battery$container$shell
[](bold white)$character'''

# Set longer timeout (avoid git command timeout)
command_timeout = 2000

[time]
disabled = false
time_format = "%F %T"
format = '[$time](dimmed blue)'

[cmd_duration]
style = 'bold blue'

[directory]
style = 'bold blue'

[git_branch]
format = '[$symbol$branch(:$remote_branch)](bold white) '

[package]
format = '[$version](dimmed blue) '

[character]
success_symbol = '[❯](bold white)'
error_symbol = '[❯](bold #bf616a)'
vimcmd_symbol = '[❯](bold white)'
