return {
	"Aurora",
	"BlulocoDark",
	"DoomOne",
	"Earthsong",
	"Espresso Libre",
	"Fahrenheit",
	"Fideloper",
	"Firewatch",
	"ForestBlue",
	"FunForrest",
	"GitHub Dark",
	"Gotham",
	"Grape",
	"Gruvbox Dark",
	"IC_Orange_PPL",
	"JetBrains Darcula",
	"MaterialOcean",
	"MonaLisa",
	"SeaShells",
	"Seafoam Pastel",
	"Shaman",
	"Slate",
	"SleepyHollow",
	"Spacedust",
	"Subliminal",
	"Thayer Bright",
	"Tinacious Design (Dark)",
	"Tomorrow Night",
	"Tomorrow Night Burns",
	"Tomorrow Night Eighties",
	"Twilight",
	"ayu",
	"iceberg-dark",
	"jubi",
	"matrix",
	"nord",
}
