--manager
require 'plugins/managers/index'

--in use
require 'plugins/settings/aerial'
require 'plugins/settings/dadbod'
require 'plugins/settings/dap'
require 'plugins/settings/dashboard'
require 'plugins/settings/fzf'
require 'plugins/settings/indentline'
require 'plugins/settings/lsp/index'
require 'plugins/settings/lualine'
require 'plugins/settings/neotest'
require 'plugins/settings/nvim-web-devicons'
require 'plugins/settings/oil'
require 'plugins/settings/peek'
require 'plugins/settings/splitjoin'
require 'plugins/settings/telescope'
require 'plugins/settings/treesitter'
require 'plugins/settings/trouble'
require 'plugins/settings/utilisnips'
require 'plugins/settings/vim-gitgutter'
