alias deps="jq '{dependencies, devDependencies, peerDependencies}'"
alias e="edit"
alias ea="$EDITOR $XDG_CONFIG_HOME/zsh/aliases.zsh"
alias ec="$EDITOR $XDG_CONFIG_HOME"
alias ed="$EDITOR $DOTFILE_DIR"
alias edit="$EDITOR"
alias eg="$EDITOR $XDG_CONFIG_HOME/git/config"
alias email="$EMAIL"
alias en="$EDITOR $XDG_CONFIG_HOME/nvim"
alias et="$EDITOR $XDG_CONFIG_HOME/tmux/tmux.conf"
alias ew="$EDITOR $XDG_CONFIG_HOME/wezterm/wezterm.lua"
alias ez="$EDITOR $XDG_CONFIG_HOME/zsh/config.zsh"
alias eza="eza --icons -a"
alias fsc="npm run cl:scopes -- -q $1"
alias gfd="fuzzy_diff"
alias gt="git"
alias gtl="git lg"
alias gtf="git fetch -ap"
alias gtp="git pull"
alias jc="jira issue create"
alias js="jira issue list -a $(jira me) -q 'Sprint in openSprints() and statusCategory != \"Done\"' --columns key,status,summary --order-by rank --reverse"
alias jsp="jira issue list -a $(jira me) -q 'Sprint in openSprints() and statusCategory != \"Done\"' --columns key,status,summary --order-by rank --reverse --plain"
alias jsa="jira issue list -a $(jira me) -q 'Sprint in openSprints()' --columns key,status,summary --order-by rank --reverse"
alias jsi="jira issue list -a $(jira me) -q 'Sprint in openSprints() and status = \"In Progress\"' --columns key,status,summary --order-by rank --reverse"
alias jlw="jira issue list -a $(jira me) -q 'statusCategory != \"To Do\" and status changed by currentUser() AFTER startOfDay(\"-7\")'"
alias jso="js --plain --columns key,labels | python3 $SCRIPTS_DIR/obsidian-helpers/fillStandupItem.py | pbcopy"
alias jsao="jsa --plain --columns key,labels | python3 $SCRIPTS_DIR/obsidian-helpers/fillStandupItem.py | pbcopy"
alias jlwo="jlw --plain --columns key,labels | python3 $SCRIPTS_DIR/obsidian-helpers/fillStandupItem.py | pbcopy"
alias jio="list_one_ticket_obsidian"
alias ji="jira issue view"
alias jis="get_ticket_status"
alias jil="list_one_ticket"
alias jim="jira issue move"
alias lc="ls $XDG_CONFIG_HOME"
alias lg="lazygit"
alias lt="eza --tree --level=2"
alias mem="cat $HOME/Documents/reference/memory-reference.txt"
alias n="nnn -A"
alias nn="n && ncd"
alias nv="nvm"
alias rl="reload"
alias s="sesh connect"
alias start="start_ticket"
alias tknote="python3 $SCRIPTS_DIR/obsidian-helpers/allTicket.py"
alias tk="tmux kill-ses"
alias tl="tmux ls"
alias tn="tmux new -s (pwd | sed 's/.*\///g')"
alias weather="curl 'wttr.in/austin?mnQF1'"
alias weathero="curl 'wttr.in/austin?m&format=%t+%p+%m+%M\n'"
alias wtcl="cat $XDG_CONFIG_HOME/wezterm/color_schemes.txt"
alias wtfs="grep font_size $XDG_CONFIG_HOME/wezterm/wezterm.lua"

# OP Vault
if [[ $AMJ_USING_OP == true ]]; then
alias npm="op run -- npm"
alias sgpt="op run -- sgpt"
fi

